/* This file is generated by npm run sync:plugins. Do not edit by hand. */
import type { FieldSpecPlugin } from '$lib/core';


type PluginModule = Record<string, unknown>;
type DesignUiKey = 'icon' | 'preview' | 'settings';

function hasOwnValue(value: object, key: DesignUiKey): boolean {
	return Object.prototype.hasOwnProperty.call(value, key) && (value as Record<DesignUiKey, unknown>)[key] != null;
}

function hasValidDesignUiGroup(value: object): boolean {
	const hasIcon = hasOwnValue(value, 'icon');
	const hasPreview = hasOwnValue(value, 'preview');
	const hasSettings = hasOwnValue(value, 'settings');
	return (hasIcon && hasPreview && hasSettings) || (!hasIcon && !hasPreview && !hasSettings);
}

function isFieldPlugin(value: unknown): value is FieldSpecPlugin<any> {
	return Boolean(
		value &&
		typeof value === 'object' &&
		typeof (value as FieldSpecPlugin<any>).type === 'string' &&
		typeof (value as FieldSpecPlugin<any>).widgetName === 'string' &&
		typeof (value as FieldSpecPlugin<any>).instance === 'function' &&
		typeof (value as FieldSpecPlugin<any>).defaultValue === 'function' &&
		hasValidDesignUiGroup(value)
	);
}

function collectPlugins(module: PluginModule): FieldSpecPlugin<any>[] {
	const collected: FieldSpecPlugin<any>[] = [];
	const candidates = [module.default, module.plugin, module.plugins];

	for (const candidate of candidates) {
		if (Array.isArray(candidate)) {
			collected.push(...candidate.filter(isFieldPlugin));
		} else if (isFieldPlugin(candidate)) {
			collected.push(candidate);
		}
	}

	for (const [key, value] of Object.entries(module)) {
		if (key.endsWith('Plugin') && isFieldPlugin(value)) {
			collected.push(value);
		}
	}

	return Array.from(new Map(collected.map((plugin) => [plugin.type, plugin])).values());
}

const customPluginModules: PluginModule[] = [];

export const customPlugins: FieldSpecPlugin<any>[] = customPluginModules.flatMap(collectPlugins);

// No custom plugins discovered.
