/* This file is generated by npm run sync:plugins. Do not edit by hand. */
import type { FieldPlugin } from '$lib/core';


type PluginModule = Record<string, unknown>;

function isFieldPlugin(value: unknown): value is FieldPlugin<any> {
	return Boolean(
		value &&
		typeof value === 'object' &&
		typeof (value as FieldPlugin<any>).type === 'string' &&
		typeof (value as FieldPlugin<any>).widgetName === 'string' &&
		typeof (value as FieldPlugin<any>).defaultValue === 'function'
	);
}

function collectPlugins(module: PluginModule): FieldPlugin<any>[] {
	const collected: FieldPlugin<any>[] = [];
	const candidates = [module.default, module.plugin, module.plugins];

	for (const candidate of candidates) {
		if (Array.isArray(candidate)) {
			collected.push(...candidate.filter(isFieldPlugin));
		} else if (isFieldPlugin(candidate)) {
			collected.push(candidate);
		}
	}

	for (const [key, value] of Object.entries(module)) {
		if (key.endsWith('Plugin') && isFieldPlugin(value)) {
			collected.push(value);
		}
	}

	return Array.from(new Map(collected.map((plugin) => [plugin.type, plugin])).values());
}

const customPluginModules: PluginModule[] = [];

export const customPlugins: FieldPlugin<any>[] = customPluginModules.flatMap(collectPlugins);

// No custom plugins discovered.
