import {
	existsSync,
	mkdirSync,
	readdirSync,
	readFileSync,
	rmSync,
	symlinkSync,
	writeFileSync
} from 'node:fs';
import { homedir } from 'node:os';
import { extname, isAbsolute, join, relative, resolve, sep } from 'node:path';

const workspaceRoot = resolve(import.meta.dirname, '..');
const pluginRoot = process.env.KERP_FORM_PLUGINS_DIR || join(homedir(), '.kerp', 'form_plugins');
const generatedRoot = join(workspaceRoot, 'src', 'lib', 'plugins');
const customLinkRoot = join(generatedRoot, '.custom');
const outputFile = join(generatedRoot, 'custom.generated.ts');
const supportedExtensions = new Set(['.js', '.mjs', '.ts', '.svelte']);

function readJson(filePath) {
	try {
		return JSON.parse(readFileSync(filePath, 'utf8'));
	} catch {
		return null;
	}
}

function normalizeEntry(pluginDir, entry) {
	if (!entry || typeof entry !== 'string') return null;
	const absolute = isAbsolute(entry) ? entry : join(pluginDir, entry);
	return existsSync(absolute) && supportedExtensions.has(extname(absolute)) ? absolute : null;
}

function findEntry(pluginDir) {
	const pkg = readJson(join(pluginDir, 'package.json'));
	const configuredEntry =
		pkg?.kerpFormPlugin?.entry ||
		pkg?.formbuilder?.entry ||
		pkg?.svelte ||
		pkg?.module ||
		pkg?.main;

	const explicitEntry = normalizeEntry(pluginDir, configuredEntry);
	if (explicitEntry) return explicitEntry;

	const candidates = [
		'index.ts',
		'index.js',
		'index.mjs',
		'src/index.ts',
		'src/index.js',
		'dist/index.js',
		'dist/index.mjs'
	];

	for (const candidate of candidates) {
		const entry = normalizeEntry(pluginDir, candidate);
		if (entry) return entry;
	}

	return null;
}

function discoverPlugins() {
	if (!existsSync(pluginRoot)) return [];

	return readdirSync(pluginRoot, { withFileTypes: true })
		.filter((entry) => entry.isDirectory())
		.map((entry) => {
			const pluginDir = join(pluginRoot, entry.name);
			const pluginEntry = findEntry(pluginDir);
			return pluginEntry
				? {
						name: entry.name,
						dir: pluginDir,
						entry: pluginEntry
					}
				: null;
		})
		.filter(Boolean);
}

function resetCustomLinkRoot() {
	rmSync(customLinkRoot, { recursive: true, force: true });
	mkdirSync(customLinkRoot, { recursive: true });
}

function createLinkedImports(discoveredPlugins) {
	resetCustomLinkRoot();

	return discoveredPlugins.map((plugin) => {
		const linkName = plugin.name.replace(/[^a-zA-Z0-9_.-]/g, '_');
		const linkPath = join(customLinkRoot, linkName);
		symlinkSync(plugin.dir, linkPath, 'dir');

		const entryRelativeToPlugin = relative(plugin.dir, plugin.entry);
		const linkedEntry = join(linkPath, entryRelativeToPlugin);
		const importPath = './' + relative(generatedRoot, linkedEntry).split(sep).join('/');

		return { ...plugin, importPath };
	});
}

function renderGenerated(discoveredPlugins) {
	const imports = discoveredPlugins
		.map((plugin, index) => `import * as pluginModule${index} from '${plugin.importPath}';`)
		.join('\n');

	const modules = discoveredPlugins.map((_, index) => `pluginModule${index}`).join(', ');
	const sourceList = discoveredPlugins
		.map((plugin) => `// - ${plugin.name}: ${plugin.entry}`)
		.join('\n');

	return `/* This file is generated by npm run sync:plugins. Do not edit by hand. */
import type { FieldPlugin } from '$lib/core';
${imports}

type PluginModule = Record<string, unknown>;

function isFieldPlugin(value: unknown): value is FieldPlugin<any> {
\treturn Boolean(
\t\tvalue &&
\t\ttypeof value === 'object' &&
\t\ttypeof (value as FieldPlugin<any>).type === 'string' &&
\t\ttypeof (value as FieldPlugin<any>).widgetName === 'string' &&
\t\ttypeof (value as FieldPlugin<any>).defaultValue === 'function'
\t);
}

function collectPlugins(module: PluginModule): FieldPlugin<any>[] {
\tconst collected: FieldPlugin<any>[] = [];
\tconst candidates = [module.default, module.plugin, module.plugins];

\tfor (const candidate of candidates) {
\t\tif (Array.isArray(candidate)) {
\t\t\tcollected.push(...candidate.filter(isFieldPlugin));
\t\t} else if (isFieldPlugin(candidate)) {
\t\t\tcollected.push(candidate);
\t\t}
\t}

\tfor (const [key, value] of Object.entries(module)) {
\t\tif (key.endsWith('Plugin') && isFieldPlugin(value)) {
\t\t\tcollected.push(value);
\t\t}
\t}

\treturn Array.from(new Map(collected.map((plugin) => [plugin.type, plugin])).values());
}

const customPluginModules: PluginModule[] = [${modules}];

export const customPlugins: FieldPlugin<any>[] = customPluginModules.flatMap(collectPlugins);

${sourceList || '// No custom plugins discovered.'}
`;
}

mkdirSync(generatedRoot, { recursive: true });
const discoveredPlugins = createLinkedImports(discoverPlugins());
writeFileSync(outputFile, renderGenerated(discoveredPlugins));

console.log(
	`Synced ${discoveredPlugins.length} custom form plugin${
		discoveredPlugins.length === 1 ? '' : 's'
	} from ${pluginRoot}`
);
